/**
 * Google Maps Link Generation Utility
 * 
 * This utility generates clean Google Maps direction links per day.
 * Filters out cab/travel blocks and duplicate coordinates to avoid messy loops.
 * Uses only actual destination blocks (restaurants, activities, attractions, etc.)
 * 
 * UPDATED: Now works with the new schema format (activities instead of blocks)
 */

/**
 * Generate a Google Maps directions link for a single day's locations
 * 
 * Filters out transport activities and removes duplicate consecutive
 * coordinates to create clean routes with only actual destinations
 * 
 * UPDATED: Works with new schema where each day has activities[] with nested activity.latitude/longitude
 */
function generateDayMapLink(activities: any[]): string | undefined {
  // Get all activities with coordinates, excluding transportation
  const locationsWithCoords = activities
    .filter(activity => 
      activity.activity?.latitude && 
      activity.activity?.longitude && 
      activity.type !== "transportation" // Skip transportation blocks
    )
    .map(activity => ({
      name: activity.activity.name,
      lat: activity.activity.latitude,
      lng: activity.activity.longitude,
    }));

  // Remove duplicate consecutive coordinates to avoid loops
  const uniqueLocations = locationsWithCoords.filter((loc, index) => {
    if (index === 0) return true;
    const prev = locationsWithCoords[index - 1];
    return loc.lat !== prev.lat || loc.lng !== prev.lng;
  });

  // Need at least 2 locations to create a route
  if (uniqueLocations.length < 2) {
    return undefined;
  }

  const origin = uniqueLocations[0];
  const destination = uniqueLocations[uniqueLocations.length - 1];
  const waypoints = uniqueLocations.slice(1, -1);

  const originParam = `${origin.lat},${origin.lng}`;
  const destinationParam = `${destination.lat},${destination.lng}`;
  const waypointsParam = waypoints.map(w => `${w.lat},${w.lng}`).join('|');

  let url = `https://www.google.com/maps/dir/?api=1&origin=${originParam}&destination=${destinationParam}`;
  
  if (waypointsParam) {
    url += `&waypoints=${waypointsParam}`;
  }
  
  url += `&travelmode=driving`;

  return url;
}

/**
 * Add map links to each day in the trip plan if user requested them
 * 
 * Main integration point - called after AI generates the plan.
 * Uses keyword detection to determine if user wants map links.
 * Programmatically generates one clean Google Maps URL per day.
 * 
 * UPDATED: Works with new schema format (days have activities[] instead of blocks[])
 * 
 * @param plan - The trip plan generated by AI (new schema format)
 * @param userWantsMap - True if user's prompt included map-related keywords
 * @returns Updated plan with mapLink added to each day (if requested)
 */
export function addMapLinksToTripPlan(plan: any, userWantsMap: boolean): any {
  if (!userWantsMap || !plan.days) {
    return plan;
  }

  // Add mapLink to each day (new schema has activities[] instead of blocks[])
  const daysWithMapLinks = plan.days.map((day: any) => ({
    ...day,
    mapLink: day.activities ? generateDayMapLink(day.activities) : undefined,
  }));

  return {
    ...plan,
    days: daysWithMapLinks,
  };
}
