import type { TripPlan } from "../schemas/trip-plan.schema.js";

/**
 * ARIA: Google Maps Link Generation Utility
 * 
 * This utility generates clean Google Maps direction links per day.
 * Filters out cab/travel blocks and duplicate coordinates to avoid messy loops.
 * Uses only actual destination blocks (restaurants, activities, sightseeing, etc.)
 * 
 * @author Aria
 */

/**
 * Generate a Google Maps directions link for a single day's locations
 * 
 * ARIA: Filters out transport blocks (cab/travel) and removes duplicate consecutive
 * coordinates to create clean routes with only actual destinations
 */
function generateDayMapLink(blocks: TripPlan["days"][0]["blocks"]): string | undefined {
  // Get all blocks with coordinates, excluding cab blocks (they're transport, not destinations)
  const locationsWithCoords = blocks
    .filter(block => 
      block.latitude && 
      block.longitude && 
      block.type !== "cab" && // Skip cab blocks
      block.type !== "travel" // Skip generic travel blocks
    )
    .map(block => ({
      name: block.title,
      lat: block.latitude!,
      lng: block.longitude!,
    }));

  // Remove duplicate consecutive coordinates to avoid loops
  const uniqueLocations = locationsWithCoords.filter((loc, index) => {
    if (index === 0) return true;
    const prev = locationsWithCoords[index - 1];
    return loc.lat !== prev.lat || loc.lng !== prev.lng;
  });

  // Need at least 2 locations to create a route
  if (uniqueLocations.length < 2) {
    return undefined;
  }

  const origin = uniqueLocations[0];
  const destination = uniqueLocations[uniqueLocations.length - 1];
  const waypoints = uniqueLocations.slice(1, -1);

  const originParam = `${origin.lat},${origin.lng}`;
  const destinationParam = `${destination.lat},${destination.lng}`;
  const waypointsParam = waypoints.map(w => `${w.lat},${w.lng}`).join('|');

  let url = `https://www.google.com/maps/dir/?api=1&origin=${originParam}&destination=${destinationParam}`;
  
  if (waypointsParam) {
    url += `&waypoints=${waypointsParam}`;
  }
  
  url += `&travelmode=driving`;

  return url;
}

/**
 * Add map links to each day in the trip plan if user requested them
 * 
 * ARIA: Main integration point - called after AI generates the plan.
 * Uses keyword detection to determine if user wants map links.
 * Programmatically generates one clean Google Maps URL per day.
 * 
 * @param plan - The trip plan generated by AI
 * @param userWantsMap - True if user's prompt included map-related keywords
 * @returns Updated plan with mapLink added to each day (if requested)
 */
export function addMapLinksToTripPlan(plan: TripPlan, userWantsMap: boolean): TripPlan {
  if (!userWantsMap) {
    return plan;
  }

  // Add mapLink to each day
  const daysWithMapLinks = plan.days.map(day => ({
    ...day,
    mapLink: generateDayMapLink(day.blocks),
  }));

  return {
    ...plan,
    days: daysWithMapLinks,
  };
}
